[features]
seeds = false
[programs.localnet]
crunchy_vs_smooth = "7dJxpeqJYp8rQt3mmV8Y8xp5pKcnbPqzht4T4its77hG"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/aoikurokawa/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
